name = "ACFlow"
uuid = "4591c03f-a9fd-4dd5-9295-2205d2683a10"
authors = ["Li Huang <huangli@caep.cn>"]
version = "2.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Dates = "1.11.0"
DelimitedFiles = "1.9.1"
Distributed = "1.11.0"
LinearAlgebra = "1.12.0"
Printf = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
TOML = "1.0.3"
Zygote = "0.7.10"
